### ISSUE TITLE
metrics not giving useful information

### ISSUE THREAD

**Issue by zllovesuki** [moleculerjs/moleculer-web#105]
When using `moleculer-web` with `moleculer-elastic-apm`, everything just said `[service].rest` instead of the actual calls. Is there a way to trace actual service call?

**Comment by icebob** [comment]
Is it same with Moleculer 0.9.0?

**Comment by intech** [comment]
> When using `moleculer-web` with `moleculer-elastic-apm`, everything just said `[service].rest` instead of the actual calls. Is there a way to trace actual service call?

In the current implementation, this cannot be done due to the old elastic apm, which did not support the microservice architecture and there was no possibility to keep track of nested queries, they were lost. That is why I made only the top level for requests for a moleculer-web.

I remember your interest in the project and will surely complete its update in accordance with the new capabilities of the musler metrics and elastic apm with opentracing support. Sorry for the long wait.

**Comment by zllovesuki** [comment]
@intech thank you for your contribution
