### ISSUE TITLE
docs for alias passReqResToParams

### ISSUE THREAD

**Issue by intech** [moleculerjs/moleculer-web#136]
Add to documentation.
```js
"GET reqres": {
  action: "test.reqres",
  passReqResToParams: true
},
```
example user-agent:
```js
const ua = ctx.params.$req.headers["user-agent"];
```

**Comment by intech** [comment]
or remove from code =)

**Comment by icebob** [comment]
It was a private stuff, only API gateway used it internally in previous versions :) The reason is, that `req` & `res` can't be correctly serializable, so you can't send them to a remote node.

**Comment by intech** [comment]
> It was a private stuff, only API gateway used it internally in previous versions :) The reason is, that `req` & `res` can't be correctly serializable, so you can't send them to a remote node.

I did not think about the remote call.
So the second option is deletion? Deprecated.

**Comment by icebob** [comment]
Yes, I will remove it even before stable 0.9

**Comment by rishighan** [comment]
Maybe there is a use case for making the `req` and `res` objects available to service actions?
I can't think of one, other than maybe file uploads, where it would be easy to get the request body and pass it on to file upload modules.

I was working with creating a simple assets service, with an upload action using the `moleculer-web` gateway module. I think I have hit a wall with passing it `FormData`, since I cannot get it in `context.params`. I get an empty object every single time. 

My service signature looks like this:

```javascript
"use strict";

module.exports = {
	name: "assets",
	version: 1,
	settings: {

	},
	dependencies: [],
	actions: {
		upload: {
			cache: {
				keys: [],
			},
			params: {
				// file: { type: "file", optional: false } ,

			},
			handler(context) {
				console.log(context.params); // always empty :(
				const params = {
					Bucket: awsCredentials.parsed.S3_BUCKET_NAME,
					Body: context.params,
					Key: "key",
				};
				s3.upload(params, (error, data) => {
					console.log(error, data);
				});

			}
		}
	},	
};
```

My API gateway:

```javascript
"use strict";

const ApiGateway = require("moleculer-web");

module.exports = {
	mixins: [ApiGateway],
	name: "api",
	settings: {
		port: process.env.PORT || 3030,
		routes: [{
			path: "/api",
		}],
		// Parse body content
		bodyParsers: {
			json: false, 
			urlencoded: false,
		},

		aliases: {
			"POST /assets/upload": {
				action: "assets.upload",
				passReqResToParams: true,
			},	
		},
		busboyConfig: {
			limits: {
				files: 1
			}
		},
		mappingPolicy: "restrict",
	},
};

```

Maybe my problem is completely unrelated to this thread, and if so, I will create an issue for it.

**Comment by icebob** [comment]
FormData fields is available in `ctx.meta.$multipart`. Relevant PR #132

**Comment by intech** [comment]
@icebob needs add to docs

**Comment by icebob** [comment]
Yes, it will come when beta will be stable.

**Comment by rishighan** [comment]
Thanks for the quick replies! Do I need the beta then?

**Comment by icebob** [comment]
Yes
