### ISSUE TITLE
Unable to use the express middlewares with moleculer js 

### ISSUE THREAD

**Issue by Moulali1995** [moleculerjs/moleculer-web#155]
Here is a simple example:
```js
// services/www.service.js
"use strict";

const express = require("express");
const ApiGateway = require("moleculer-web");

module.exports = {
    name: "www",
    mixins: [ApiGateway],

    settings: {
        port: process.env.PORT || 3000,
aliases:{
// Custom aliases
'GET /user';'user.find',
.....

            }
    },

    created() {
        const app = express();
       app.use(session({})) // i'm using express-session with redis. This middleware is not called when a request is made.
        app.use(this.express());

        this.app = app;
    },

    started() {
        this.app.listen(Number(this.settings.port), err => {
            if (err)
                return this.broker.fatal(err);

            this.logger.info(`WWW server started on port ${this.settings.port}`);
        });

    },

    stopped() {
        if (this.app.listening) {
            this.app.close(err => {
                if (err)
                    return this.logger.error("WWW server close error!", err);

                this.logger.info("WWW server stopped!");
            });
        }
    }
};
```

_Originally posted by @icebob in https://github.com/moleculerjs/moleculer-web/issues/69#issuecomment-409893546_

**Comment by AndreMaz** [comment]
What's the version of `molecule-web` are you using?
Also, looking at the code it seems that you are starting `ApiGateway` and the `express` at the same port so you should get `EADDRINUSE` error.

The middleware is working fine over here
![image](https://user-images.githubusercontent.com/9802754/69532047-efa9f900-0f6c-11ea-96da-12bda7005031.png)

**Comment by moulali1947** [comment]
I'm using the following versions
 "moleculer": "^0.13.0",  // Moleculer v0.13.7 is starting
"moleculer-web": "^0.8.0",

I'm not getting any error while moleculer and express both are running on the same port maybe because either of them is running internally and are binded on that port for listening.
I'll try with your solution of using middleware.
will it work with aliases?

**Comment by AndreMaz** [comment]
Ok, so now I think I understand what you want to achieve. Check this: https://moleculer.services/docs/0.13/moleculer-web.html#ExpressJS-middleware-usage

Also, you should update `moleculer-web` to latest version. A lot of things have changed (https://github.com/moleculerjs/moleculer-web/blob/master/CHANGELOG.md#080-2018-07-08) since v0.8.0

**Comment by moulali1947** [comment]
If i use the first link as a solution: In this broker is created and started manually by the user. I want the moleculer runner to create broker and start the services.

And i want to use express just for express-session and redis-store. Now after creating the middleware it seems like the the session aren't getting stored in redis store.

At route level i have aliases and want to store sessions when the user login and send that session data inside the cookie which is basically done by the express-session or do i need to send a custom cookie and if this is the case how can i access the redis store data to create the cookie?

**Comment by AndreMaz** [comment]
Just to be clear, you want to use `moleculer-web` + some `express`-based middleware, right? In this case you don't need express to start HTTP server (as you've done in https://github.com/moleculerjs/moleculer-web/issues/155#issue-527962281) because `moleculer-web` starts one (a node.js native HTTP server).  While using a native HTTP server (not the express), `moleculer-web` middlewares have the same signature as `express` middleware. This means that you should be able to use any `express`-based middleware with `moleculer-web` without any issue. 
For example, in https://github.com/moleculerjs/moleculer-web/issues/96#issuecomment-539670254 I've added 2 middlewares to the `api.service.js`@[moleculer-demo](https://moleculer.services/docs/0.13/usage.html#Create-a-Moleculer-project)

**Comment by moulali1947** [comment]
<img width="343" alt="Capture" src="https://user-images.githubusercontent.com/17765871/69845959-7b3ac700-1298-11ea-8d14-34bfd81740cd.PNG">


Thanks @AndreMaz for the express server free solution. now i'm able to use the middleware with use:[] but the problem is redis store after a request their is no log of session in redis cli monitor and cookie is not sent to the client.
When tried the same approach in express it was working the cookie was sent to the client and redis store cli monitor was showing the logs of sessions.
<img width="451" alt="redis_monitor" src="https://user-images.githubusercontent.com/17765871/69846232-6e6aa300-1299-11ea-8da4-370453d180c1.PNG">
<img width="398" alt="cookie" src="https://user-images.githubusercontent.com/17765871/69846241-732f5700-1299-11ea-9377-db16c8360c49.PNG">


Please refer to the attached screenshots of the redis store issue.
Can you help me out here?

**Comment by AndreMaz** [comment]
Hey @moulali1947 . Sorry but I'm on vacation right now so I can't help you. Have tried to debug your app and see what happens in middlewares?

**Comment by Moulali1995** [comment]
Can you help me out?
