### ISSUE TITLE
Molecular-web framework is not consuming distributed tracing request headers passed from an external web service.

### ISSUE THREAD

**Issue by Shal10** [moleculerjs/moleculer-web#51]
I am making a REST call from an external web service (which is using spring-sleuth for distributed tracing at zipkin) to a node js microservice (which is using molecular-web framework), service is being called and result is returned however moleculer-web is not consuming x-b3-traceid & x-b3-spanid request headers used for distributed tracing and the tracing is working only when services are invoked using the broker directly.

Since the headers are not consumed by the called service, there is no tracing linking between these two services. Ideally, the called service should have caller service's id as parent id but in this case that is not happening, they are generating separate tracing graphs.

Additionally, the parent context is being created only when the it is called thru molecular node js service.
**node-js-service.js:**
.
.
.
actions: {
		create(ctx) {
			ctx.call("any-service", {
.
.
.

**context.js:**
.
.
.
call(actionName, params, opts = {}) {
		opts.parentCtx = this;
.
.
.

**Comment by Shal10** [comment]
API Gateway - route hooks did wonders 🥇 #49 
https://moleculer.services/0.12/docs/moleculer-web.html#Route-hooks

`routes: [{
             path: "/api",
             onBeforeCall(ctx, route, req, res) {
                    ctx.parentID = req.headers["x-b3-spanid"];
                    ctx.requestID = req.headers["x-b3-traceid"];
},`

**Comment by synsteve** [comment]
Hi, sorry to resurrect an old issue, but I am looking to establish distributed tracing between several moleculer apps.  I used x-correlation-id with some success but this doesn't work with spans.  I've tried the onBeforeCall and using a custom mw but because these are invoked after the call to the rest action, I can't set the ctx.parentID to marry it up to the calling span.

Am I missing something?
