### ISSUE TITLE
Authentication step

### ISSUE THREAD

**Issue by alebertacco** [moleculerjs/moleculer-web#73]
I'm playing with moleculer-web, in particular with the authentication and authorization part.
If I'm not wrong, with the current implementation is only possible to make the authentication directly within the authorization part. Another option is to put the authentication step in an onBeforeCall hook.

What do you think about creating an authentication facility? Similar to what there is already for the authorization.

I've already done some tweak on the module, but I would prefer to listen your opinion before creating a pull request.

Thanks,
Ale

**Comment by icebob** [comment]
The authentication can be a middleware or a service because don't need to process it before processing the request. However, authorization must be processed before the request is processed (check that the user is logged in and has appropriate rights). In my projects, I'm using services for authentication and using `authorize` for authorization.

By the way, show some code what do you think to create.

**Comment by alebertacco** [comment]
Just add a pull request with the required code. Let me know if it's ok for you, in that case I can try to add also documentation and examples.

**Comment by tiaod** [comment]
@icebob I think the current version what `authentication` do is very similar to `authorization`, the new `authentication` handler just save the result to `ctx.meta.user`, which can also be done by authorization handler. **Why it is necessary to add a new authentication handler? Why the user info must save to `ctx.meta.user`?**

**Comment by icebob** [comment]
No need to use them. Both are same. But it can be useful if you use mixins. E.g. you have an `AuthMixin` which implement the `authentication` method and have an `AuthorizeMixin` which implements the `authorize` method.

**Comment by tiaod** [comment]
@icebob Fully understand, thank you patience to answer :smile:
