### ISSUE TITLE
Global middlewares not working

### ISSUE THREAD

**Issue by HASSANDL** [moleculerjs/moleculer-web#96]
I use below code but not call!
version: 0.8.5
```
settings: {
    use: [
        function (err, req, res, next) {
            console.log(req);
        },
    ],
}
```

**Comment by saeedtabrizi** [comment]
Same issue . is there any trick to resolve it ?

**Comment by icebob** [comment]
Could you try it with 0.9 beta as well?

**Comment by saeedtabrizi** [comment]
Hi @icebob ,
I was tried it by 0.9 beta 6 but same issue repeated . 
Just i copied **moleculer-web** source code in my project and translate it to typescript because i want to add some feature as below :
- add render engine (React SSR , EJS , Handlebar , ...) to the service because in my case i have some .ejs or .tsx files that i want to render via calling actions or router alias . (there is no example that how to implement render engine)
- fix calling global middlewares issue .  

Is there any trick or sample to solve them ?

**Comment by AndreMaz** [comment]
Hey @HASSANDL and @saeedtabrizi I think that the problem is that you are using wrong function signature.
It's a middleware function so it should be 
```js
function (req, res, next) {}
```
and not
```js
function (err, req, res, next) {}
```
Can you please test it and check if it works properly for you?

**Comment by saeedtabrizi** [comment]
Hi @AndreMaz 
I just test it and its ok  in code with the true signature . 
Thanks
